spring:
  application:
    name: lean-in-connect-api

  datasource:
    url: jdbc:h2:file:./data/leanin-connect;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true

server:
  port: ${PORT:8080}